### ISSUE TITLE
App crash if non-US locale is used

### ISSUE THREAD

**Issue by sulkaharo** [someoneAnyone/Nightscouter#27]
Repro:

1) Go to iOS Settings / General / Language & Region and set Region to Finland
2) Start Nightscouter and observe it crashing right after it's rendered part of the UI

**Comment by someoneAnyone** [comment]
I've reproduced the bug by setting my phone to Finland and connecting to a site that uses mmol/L. However everything seems to work ok with a mg/dL. I'll look through the logs and see what needs to be fixed.

**Comment by someoneAnyone** [comment]
The crash is occurring at: 

https://github.com/someoneAnyone/Nightscouter/blob/dev/NightscouterKit/Models/WatchEntry.swift#L121

**Comment by someoneAnyone** [comment]
Digging deeper it might be the conversion to a double in 

https://github.com/someoneAnyone/Nightscouter/blob/dev/NightscouterKit/Extensions/String%2BExtensions.swift#L39

``` swift
public var toDouble: Double? {
     return NSNumberFormatter().numberFromString(self)?.doubleValue
}
```

**Comment by someoneAnyone** [comment]
This might fix the problem....

``` swift
public extension String {
    var formatter: NSNumberFormatter {
        let formatter = NSNumberFormatter()
        formatter.locale = NSLocale.systemLocale()
        return formatter
    }

    public var floatValue: Float? {
        return formatter.numberFromString(self)?.floatValue
    }
    public var toDouble: Double? {
        return formatter.numberFromString(self)?.doubleValue
    }
}
```

**Comment by someoneAnyone** [comment]
https://github.com/someoneAnyone/Nightscouter/commit/fb943a1e05abf0f4e2a71e1968b584cbc233b2c8
