### ISSUE TITLE
Screen Lock Override

### ISSUE THREAD

**Issue by jwedding** [someoneAnyone/Nightscouter#3]
Many users use the native apps at night to trigger alarms. Need a "Screen Lock Override" to keep the app awake and keep alarms an option.

**Comment by someoneAnyone** [comment]
@jwedding, I've added a way to toggle Screen Lock Override in the settings bundle. haven't found a good spot to expose it in the UI though... What makes more sense? Make it global to the app or make it per website and only honor it when you're looking at the view with the compass and chart?
