### ISSUE TITLE
Needs Alarms

### ISSUE THREAD

**Issue by jwedding** [someoneAnyone/Nightscouter#4]
A native client could use user side alarms to have independent control. i.e. I set the low lower than my daughter does so she has time to react before I get involved.

**Comment by someoneAnyone** [comment]
Step one will be to make audible sounds based on the thresholds I get from the server. Once I get that working I'll try to add custom ones. Would you want them to POST the changes to the website? That's where I think it should probably go... That way your settings are sync across devices.

**Comment by someoneAnyone** [comment]
@jwedding - As of c8279dd4f91ade1bd4cb62b21271b2ff1b35c659 the app now color codes sgv, raw, last reading, and battery items when appropriate events are triggered. still working on audible cues to following along, but wanted to give you an update.

**Comment by someoneAnyone** [comment]
Some requirements for alarms....

An alarm should be triggered if the any the follow is true.
1. If the site has stale data and it is configured to warn about such. Server configuration can provide warn time interval and urgent interval.
2. If the T1's current BG is above or below the provided thresholds.
3. If the T1's current BG is producing an error code.
4. A user of the app should be able to silence an alarm for a set duration.
5. Only one alarm should be played a given time. Do not let multiple alarms to overlap each other.
6. Warn users that alarms will only be heard if the device is not in silent mode.

Something like...

``` Swift
if site.warn || site.urgent || site.alarmForSGV {
       // Play sound.
}
```

One idea I had was to download the alarm file form the user's website... it should probably be cached though.

``` swift
public func playAlarmFor(url: NSURL, urgent: Bool = false) {
    let assetName = urgent ? "alarm2" : "alarm"
    let audioUrl = url.URLByAppendingPathComponent("/audio/\(assetName).mp3")

    var downloadTask:NSURLSessionDownloadTask
    downloadTask = NSURLSession.sharedSession().downloadTaskWithURL(audioUrl, completionHandler: { (URL, response, error) -> Void in

        do {
            try! AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)

            alarmAudioPlayer = try AVAudioPlayer(contentsOfURL: URL!)

            alarmAudioPlayer?.prepareToPlay()
            alarmAudioPlayer?.volume = 1.0
            alarmAudioPlayer?.numberOfLoops = -1
            alarmAudioPlayer?.play()
        } catch let error as NSError {
            alarmAudioPlayer = nil
            print(error.localizedDescription)
        } catch {
            print("AVAudioPlayer init failed")
        }

    })

    downloadTask.resume()
}

```

**Comment by someoneAnyone** [comment]
Branch created. 
https://github.com/someoneAnyone/Nightscouter/tree/wip-audible-alarms

**Comment by someoneAnyone** [comment]
Moving alarm work to: https://github.com/someoneAnyone/Nightscouter/tree/pr/51

**Comment by someoneAnyone** [comment]
Alarms are working as of: https://github.com/someoneAnyone/Nightscouter/commit/87672f30c338d7a6114fc99407bcb80cd30c8f5f
