### ISSUE TITLE
Layout bugs

### ISSUE THREAD

**Issue by brutevinch** [someoneAnyone/Nightscouter#45]
![img_0913](https://cloud.githubusercontent.com/assets/12526597/15637374/23ad5836-2638-11e6-8e4b-ec56c09f411b.PNG)

**Comment by brutevinch** [comment]
1) Last reading data - make multiple string. 
2) Place Y-direction(2 number on screenshot) upper than X-direction(06 number on screenshot)
3) Graph not centered (see spacing left where is graph starting and left where is Y-direction  )
4) Main circle not centered (it must be under clocks) maybe all layout moved to left =(((

**Comment by brutevinch** [comment]
![2016-05-30 6 50 51](https://cloud.githubusercontent.com/assets/12526597/15637861/6aa6c18e-263b-11e6-82a5-a72d16d0fdc6.png)

5) This is need tweaking. But now i have no idea.... (about dots under numbers)

**Comment by brutevinch** [comment]
![img_0914](https://cloud.githubusercontent.com/assets/12526597/15637958/a5c54870-263c-11e6-8e18-efe3eb761284.PNG)
Here we have: 
6) Extra space to make graph bigger if "main circle" will be moved to left.
7) Graph not centered (spacing top and spacing bottom)
8) (Maybe??!) Back, Name, Gears not centered too.

**Comment by brutevinch** [comment]
9) On dock with dots (page indicator) maybe use main background? now it has own background but with main gradient will be more in concept.

**Comment by brutevinch** [comment]
![img_0915](https://cloud.githubusercontent.com/assets/12526597/15638310/b4c6d72c-2640-11e6-8dfd-8e7e78baa69e.PNG)

10) !?!?! =)))

**Comment by someoneAnyone** [comment]
I am moving the layout to stack views. This is a work in progress, I'll update the issue when I have a stable build.

**Comment by someoneAnyone** [comment]
Please report if the issue remains after trying latest test flight release.

**Comment by brutevinch** [comment]
Please add me to test flight brutevinch@gmail.com

**Comment by someoneAnyone** [comment]
I believe most of these issues are resolved in the latest beta. Please open new tickets if you see any issues. Thanks you!
