### ISSUE TITLE
Site Detail View Not Refreshing Network Data

### ISSUE THREAD

**Issue by someoneAnyone** [someoneAnyone/Nightscouter#48]
If the app is looking at a site's detail view. It will update the UI but it it is not triggering a network call to update the data from the server.

I believe the problem is in SiteDetailViewController.swift most likely here...

**(site.lastConnectedDate?.compare(site.nextRefreshDate) == .OrderedDescending || site.entries == nil || site.configuration == nil || force == true)**

``` swift
  func updateData(forceUpdate force: Bool = false) {
        guard let site = self.site else { return }

        if (site.lastConnectedDate?.compare(site.nextRefreshDate) == .OrderedDescending || site.entries == nil || site.configuration == nil || force == true) {

            UIApplication.sharedApplication().networkActivityIndicatorVisible = true
            self.siteActivityView?.startAnimating()

            fetchSiteData(site, handler: { (returnedSite, error) -> Void in
                AppDataManageriOS.sharedInstance.updateSite(returnedSite)
                self.updateUI()
            })
        } else {
            self.updateUI()
        }
    }
```

**Comment by toarikaplan** [comment]
The main screen with 2 T-1s does not update regularly. When I force touch and click update, sometimes it works, but it it rarely updated in "real-time." One it updates (see attached) it is great. Is this the bugfix you are working on?
![img_0036](https://cloud.githubusercontent.com/assets/8159914/18818342/567a3af2-833c-11e6-925a-74320913eb3c.PNG)

**Comment by someoneAnyone** [comment]
I am working on some fixes, the finial versions of iOS 10 and watchOS 3 have introduced some problems and I'm working through the issues.

**Comment by someoneAnyone** [comment]
I believe this working better in the latest builds. Are you on the beta? If the problem still exists please reopen this issue.
