### ISSUE TITLE
doesnt display bg info when noise isnt enabled

### ISSUE THREAD

**Issue by kenstack** [someoneAnyone/Nightscouter#5]
displays battery and minutes since last read but no bg info if noise is not enabled

**Comment by someoneAnyone** [comment]
In-progress... https://github.com/someoneAnyone/Nightscouter/commit/c369dfcfcaa322e6f1dff2b6a44288126a778247

**Comment by someoneAnyone** [comment]
@kenstack can check the app and see if things are working better?

**Comment by kenstack** [comment]
yes working better thanks I think you can close

**Comment by someoneAnyone** [comment]
Closing!
