### ISSUE TITLE
App requires manual updates to refresh data

### ISSUE THREAD

**Issue by toarikaplan** [someoneAnyone/Nightscouter#55]
The new Apple Watch version is not crashing = much more reliable. It is not updating without manually requesting an update. Is this something you are working on?

**Comment by someoneAnyone** [comment]
I'm still working on update frequency. Just let me know if your comfortable with me closing. https://github.com/someoneAnyone/Nightscouter/issues/54

**Comment by toarikaplan** [comment]
I am comfortable with you closing this. Thanks

-Ari

On Thu, Oct 6, 2016 at 9:01 PM -0500, "Pete" notifications@github.com wrote:

I'm still working on update frequency. Just let me know if your comfortable with me closing. #54
