### ISSUE TITLE
TestFlight 

### ISSUE THREAD

**Issue by Byketol** [someoneAnyone/Nightscouter#78]
Hello can i have a invitier for the TestFlight Beta App?

**Comment by someoneAnyone** [comment]
Sure, but there isn’t an active beta at the moment. Feel free to download from the AppStore or build it from the source code... specifically Dev will give you the latest but not stable version of the app.

**Comment by someoneAnyone** [comment]
When it comes time to add you, I’ll also need an email address.

**Comment by Byketol** [comment]
Hy Sry
My Mail adress is andre@family-engel.de
