### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by lgiewercer** [someoneAnyone/Nightscouter#81]

**Comment by lgiewercer** [comment]
Just got an Apple Watch series 1.
Running Nightscouter from my iPhone. 
Have a g4 dexcom.
App is not updating automatically on my watch.
Anyone know what I have done wrong?

**Comment by someoneAnyone** [comment]
Not sure. Are you building from source or from the appstore?

**Comment by lgiewercer** [comment]
App Store

Sent from my iPhone

On Apr 8, 2018, at 12:39 PM, Pete <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure. Are you building from source or from the appstore?

**Comment by someoneAnyone** [comment]
Fixed in https://github.com/someoneAnyone/Nightscouter/commit/1e611d58e264afb0cb911e0663e77607aaf9b7a5
