### ISSUE TITLE
Support for Apple Watch Series 4 Complications

### ISSUE THREAD

**Issue by snics** [someoneAnyone/Nightscouter#84]
Hi,

I would like a support for all complications of the new Series 4. Could you consider including this in a next update?

**Comment by someoneAnyone** [comment]
I'll take a look. FYI - The code is open source, and I'm accepting of PRs if you're so inclined to contribute.

**Comment by snics** [comment]
@someoneAnyone, I'm happy to try my best but unfortunately I'm not so good with swift. But it'd be something new to try out 😄
